// src/app/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {
  copyrightYear = new Date().getFullYear();
}
<footer class="page-footer p-3">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-sm-12" id="about">
				<h5 class="white-text">What is this about?</h5>
				<p class="grey-text text-lighten-4">This is a popular challenge done by
					<a target="_new" href="https://jenniferdewalt.com/">Jennifer Dewalt</a>. I'm recreating it for the purpose of learning.</p>
				<p>
					The original "180 Days challenge" is to develop a website each day and share (if interested) via any comfortable blogging platform. However, I would be slightly changing this to develop projects in my own spare time. :) 
				</p>
			</div>
		</div>
	</div>
	<div class="footer-copyright">
		<div class="container text-center">
			© <span>{{copyrightYear}}</span> - <a href="https://github.com/NitinNair89" target="_blank" title="Follow Nitin on GitHub" aria-label="Follow Nitin on GitHub">@NitinNair</a>
		</div>
	</div>
</footer>

// src/components/Footer/index.tsx
import { Link } from 'react-router-dom';

export const Footer = () => {
  return (
    <footer className="text-left text-small text-muted">
      <div>
        This is a popular challenge done by{' '}
        <Link to="https://jenniferdewalt.com/">Jennifer Dewalt</Link>.
        The "180 Days challenge" is to develop a website each day and
        upskill in the process.
      </div>
      <div>
        Made with ❤️ by{' '}
        <Link
          to="https://github.com/NitinNair89"
          target="_blank"
          title="Follow Nitin on GitHub"
          aria-label="Follow Nitin on GitHub"
        >
          Nitin Nair
        </Link>{' '}
      </div>
    </footer>
  );
};
